//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GGJWEvent.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DailyDraw
    {
        public long Id { get; set; }
        public string DrawName { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string DrawCount { get; set; }
        public string Prize { get; set; }
        public string Image { get; set; }
    }
}
