//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GGJWEvent.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DrawWinner
    {
        public long Id { get; set; }
        public Nullable<long> DrawId { get; set; }
        public Nullable<long> CustomerId { get; set; }
    }
}
