//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GGJWEvent.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class GGJWEventEntities : DbContext
    {
        public GGJWEventEntities()
            : base("name=GGJWEventEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<City> Cities { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<Draw> Draws { get; set; }
        public virtual DbSet<ExhibitorBanner> ExhibitorBanners { get; set; }
        public virtual DbSet<State> States { get; set; }
        public virtual DbSet<DrawWinner> DrawWinners { get; set; }
        public virtual DbSet<DailyDraw> DailyDraws { get; set; }
        public virtual DbSet<ApplyCoupon> ApplyCoupons { get; set; }
        public virtual DbSet<Admin> Admins { get; set; }
        public virtual DbSet<AssignCouponExhibitor> AssignCouponExhibitors { get; set; }
        public virtual DbSet<RequestForCoupon> RequestForCoupons { get; set; }
        public virtual DbSet<ExhibitorCouponQty> ExhibitorCouponQties { get; set; }
        public virtual DbSet<CustomerCoupon> CustomerCoupons { get; set; }
        public virtual DbSet<MegaDraw> MegaDraws { get; set; }
        public virtual DbSet<MegaDrawWinner> MegaDrawWinners { get; set; }
        public virtual DbSet<Notification> Notifications { get; set; }
        public virtual DbSet<Exhibitor> Exhibitors { get; set; }
    
        public virtual int UpdateExhibitorVerficationStatus(Nullable<int> status, Nullable<long> exhibitorId)
        {
            var statusParameter = status.HasValue ?
                new ObjectParameter("status", status) :
                new ObjectParameter("status", typeof(int));
    
            var exhibitorIdParameter = exhibitorId.HasValue ?
                new ObjectParameter("ExhibitorId", exhibitorId) :
                new ObjectParameter("ExhibitorId", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateExhibitorVerficationStatus", statusParameter, exhibitorIdParameter);
        }
    
        public virtual int UpdateVisitoreVerficationStatus(Nullable<int> status, Nullable<long> visitorId)
        {
            var statusParameter = status.HasValue ?
                new ObjectParameter("status", status) :
                new ObjectParameter("status", typeof(int));
    
            var visitorIdParameter = visitorId.HasValue ?
                new ObjectParameter("VisitorId", visitorId) :
                new ObjectParameter("VisitorId", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateVisitoreVerficationStatus", statusParameter, visitorIdParameter);
        }
    
        public virtual ObjectResult<GetApplyCouponCustomer_Result> GetApplyCouponCustomer()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetApplyCouponCustomer_Result>("GetApplyCouponCustomer");
        }
    
        public virtual ObjectResult<GetDrawCoupon_Result> GetDrawCoupon()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetDrawCoupon_Result>("GetDrawCoupon");
        }
    
        public virtual ObjectResult<GetMyCustomerAssignCouponData_Result> GetMyCustomerAssignCouponData(Nullable<long> exhibitorId)
        {
            var exhibitorIdParameter = exhibitorId.HasValue ?
                new ObjectParameter("ExhibitorId", exhibitorId) :
                new ObjectParameter("ExhibitorId", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetMyCustomerAssignCouponData_Result>("GetMyCustomerAssignCouponData", exhibitorIdParameter);
        }
    
        public virtual ObjectResult<GetVisitorDataByMobileOrId_Result> GetVisitorDataByMobileOrId(string mobile, Nullable<long> visitorId)
        {
            var mobileParameter = mobile != null ?
                new ObjectParameter("Mobile", mobile) :
                new ObjectParameter("Mobile", typeof(string));
    
            var visitorIdParameter = visitorId.HasValue ?
                new ObjectParameter("VisitorId", visitorId) :
                new ObjectParameter("VisitorId", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetVisitorDataByMobileOrId_Result>("GetVisitorDataByMobileOrId", mobileParameter, visitorIdParameter);
        }
    
        public virtual ObjectResult<GetVisitorLoginData_Result> GetVisitorLoginData(string mobile)
        {
            var mobileParameter = mobile != null ?
                new ObjectParameter("Mobile", mobile) :
                new ObjectParameter("Mobile", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetVisitorLoginData_Result>("GetVisitorLoginData", mobileParameter);
        }
    
        public virtual ObjectResult<GetExhibitorBannerData_Result> GetExhibitorBannerData()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetExhibitorBannerData_Result>("GetExhibitorBannerData");
        }
    
        public virtual ObjectResult<GetRequestForCoupon_Result> GetRequestForCoupon()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetRequestForCoupon_Result>("GetRequestForCoupon");
        }
    
        public virtual ObjectResult<GetDashboardCount_Result> GetDashboardCount()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetDashboardCount_Result>("GetDashboardCount");
        }
    
        public virtual ObjectResult<GetCities_Result> GetCities()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetCities_Result>("GetCities");
        }
    
        public virtual ObjectResult<GetCouponToExhibitor_Result> GetCouponToExhibitor()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetCouponToExhibitor_Result>("GetCouponToExhibitor");
        }
    
        public virtual ObjectResult<GetCustomerData_Result> GetCustomerData()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetCustomerData_Result>("GetCustomerData");
        }
    
        public virtual ObjectResult<GetRequestCouponData_Result> GetRequestCouponData(Nullable<long> exhibitorId)
        {
            var exhibitorIdParameter = exhibitorId.HasValue ?
                new ObjectParameter("ExhibitorId", exhibitorId) :
                new ObjectParameter("ExhibitorId", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetRequestCouponData_Result>("GetRequestCouponData", exhibitorIdParameter);
        }
    
        public virtual ObjectResult<GetCustomerCouponData_Result> GetCustomerCouponData(Nullable<long> visitorId, Nullable<long> exhibitorId)
        {
            var visitorIdParameter = visitorId.HasValue ?
                new ObjectParameter("VisitorId", visitorId) :
                new ObjectParameter("VisitorId", typeof(long));
    
            var exhibitorIdParameter = exhibitorId.HasValue ?
                new ObjectParameter("ExhibitorId", exhibitorId) :
                new ObjectParameter("ExhibitorId", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetCustomerCouponData_Result>("GetCustomerCouponData", visitorIdParameter, exhibitorIdParameter);
        }
    
        public virtual ObjectResult<GetDrawWinnerListData_Result> GetDrawWinnerListData()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetDrawWinnerListData_Result>("GetDrawWinnerListData");
        }
    
        public virtual ObjectResult<GetTotalCouponData_Result> GetTotalCouponData(Nullable<long> exhibitorId)
        {
            var exhibitorIdParameter = exhibitorId.HasValue ?
                new ObjectParameter("ExhibitorId", exhibitorId) :
                new ObjectParameter("ExhibitorId", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetTotalCouponData_Result>("GetTotalCouponData", exhibitorIdParameter);
        }
    
        public virtual ObjectResult<GetDrawWinnerData_Result> GetDrawWinnerData(Nullable<long> drawId)
        {
            var drawIdParameter = drawId.HasValue ?
                new ObjectParameter("DrawId", drawId) :
                new ObjectParameter("DrawId", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetDrawWinnerData_Result>("GetDrawWinnerData", drawIdParameter);
        }
    
        public virtual int UpdateExhibitorFcmToken(Nullable<long> exhibitorId, string fCMToken)
        {
            var exhibitorIdParameter = exhibitorId.HasValue ?
                new ObjectParameter("ExhibitorId", exhibitorId) :
                new ObjectParameter("ExhibitorId", typeof(long));
    
            var fCMTokenParameter = fCMToken != null ?
                new ObjectParameter("FCMToken", fCMToken) :
                new ObjectParameter("FCMToken", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateExhibitorFcmToken", exhibitorIdParameter, fCMTokenParameter);
        }
    
        public virtual int UpdateVisitorFcmToken(Nullable<long> visitorId, string fCMToken)
        {
            var visitorIdParameter = visitorId.HasValue ?
                new ObjectParameter("VisitorId", visitorId) :
                new ObjectParameter("VisitorId", typeof(long));
    
            var fCMTokenParameter = fCMToken != null ?
                new ObjectParameter("FCMToken", fCMToken) :
                new ObjectParameter("FCMToken", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateVisitorFcmToken", visitorIdParameter, fCMTokenParameter);
        }
    
        public virtual int UpdateCustomerCouponStatus(Nullable<long> couponId)
        {
            var couponIdParameter = couponId.HasValue ?
                new ObjectParameter("CouponId", couponId) :
                new ObjectParameter("CouponId", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateCustomerCouponStatus", couponIdParameter);
        }
    
        public virtual ObjectResult<GetCoupon_Result> GetCoupon()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetCoupon_Result>("GetCoupon");
        }
    
        public virtual ObjectResult<GetMegaDrawWinnerData_Result> GetMegaDrawWinnerData()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetMegaDrawWinnerData_Result>("GetMegaDrawWinnerData");
        }
    
        public virtual ObjectResult<GetCustomerFCMToken_Result> GetCustomerFCMToken()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetCustomerFCMToken_Result>("GetCustomerFCMToken");
        }
    
        public virtual ObjectResult<GetCustomerFCMTokenMega_Result> GetCustomerFCMTokenMega()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetCustomerFCMTokenMega_Result>("GetCustomerFCMTokenMega");
        }
    
        public virtual ObjectResult<GetCouponList_Result> GetCouponList(Nullable<long> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetCouponList_Result>("GetCouponList", idParameter);
        }
    
        public virtual ObjectResult<GetCouponAssign_Result> GetCouponAssign(Nullable<long> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetCouponAssign_Result>("GetCouponAssign", idParameter);
        }
    
        public virtual ObjectResult<GetCustomerCouponDetail_Result> GetCustomerCouponDetail(Nullable<long> visitorId, Nullable<long> exhibitorId)
        {
            var visitorIdParameter = visitorId.HasValue ?
                new ObjectParameter("VisitorId", visitorId) :
                new ObjectParameter("VisitorId", typeof(long));
    
            var exhibitorIdParameter = exhibitorId.HasValue ?
                new ObjectParameter("ExhibitorId", exhibitorId) :
                new ObjectParameter("ExhibitorId", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetCustomerCouponDetail_Result>("GetCustomerCouponDetail", visitorIdParameter, exhibitorIdParameter);
        }
    
        public virtual ObjectResult<GetAssignedCoupons_Result> GetAssignedCoupons()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAssignedCoupons_Result>("GetAssignedCoupons");
        }
    
        public virtual ObjectResult<GetcustomerCouponByExhibitorIdData_Result> GetcustomerCouponByExhibitorIdData(Nullable<long> exhibitorId)
        {
            var exhibitorIdParameter = exhibitorId.HasValue ?
                new ObjectParameter("ExhibitorId", exhibitorId) :
                new ObjectParameter("ExhibitorId", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetcustomerCouponByExhibitorIdData_Result>("GetcustomerCouponByExhibitorIdData", exhibitorIdParameter);
        }
    
        public virtual int UpdateAssignCouponExhibitor(Nullable<long> id, Nullable<long> exhibitorId, string qty, string total)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(long));
    
            var exhibitorIdParameter = exhibitorId.HasValue ?
                new ObjectParameter("ExhibitorId", exhibitorId) :
                new ObjectParameter("ExhibitorId", typeof(long));
    
            var qtyParameter = qty != null ?
                new ObjectParameter("Qty", qty) :
                new ObjectParameter("Qty", typeof(string));
    
            var totalParameter = total != null ?
                new ObjectParameter("Total", total) :
                new ObjectParameter("Total", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateAssignCouponExhibitor", idParameter, exhibitorIdParameter, qtyParameter, totalParameter);
        }
    
        public virtual ObjectResult<GetCustomerCouponHistoryData_Result> GetCustomerCouponHistoryData()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetCustomerCouponHistoryData_Result>("GetCustomerCouponHistoryData");
        }
    
        public virtual ObjectResult<GetExhibitorByCustomerCoupon_Result> GetExhibitorByCustomerCoupon(Nullable<long> visitorId)
        {
            var visitorIdParameter = visitorId.HasValue ?
                new ObjectParameter("VisitorId", visitorId) :
                new ObjectParameter("VisitorId", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetExhibitorByCustomerCoupon_Result>("GetExhibitorByCustomerCoupon", visitorIdParameter);
        }
    
        public virtual ObjectResult<GetCusmoterMobile_Result> GetCusmoterMobile(Nullable<long> vistorId)
        {
            var vistorIdParameter = vistorId.HasValue ?
                new ObjectParameter("VistorId", vistorId) :
                new ObjectParameter("VistorId", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetCusmoterMobile_Result>("GetCusmoterMobile", vistorIdParameter);
        }
    
        public virtual ObjectResult<GetExhibitorMobileno_Result> GetExhibitorMobileno(Nullable<long> exhibitorId)
        {
            var exhibitorIdParameter = exhibitorId.HasValue ?
                new ObjectParameter("ExhibitorId", exhibitorId) :
                new ObjectParameter("ExhibitorId", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetExhibitorMobileno_Result>("GetExhibitorMobileno", exhibitorIdParameter);
        }
    
        public virtual ObjectResult<GetCouponDetail_Result> GetCouponDetail()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetCouponDetail_Result>("GetCouponDetail");
        }
    
        public virtual ObjectResult<GetExhibitorLoginData_Result> GetExhibitorLoginData(string mobile)
        {
            var mobileParameter = mobile != null ?
                new ObjectParameter("Mobile", mobile) :
                new ObjectParameter("Mobile", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetExhibitorLoginData_Result>("GetExhibitorLoginData", mobileParameter);
        }
    
        public virtual ObjectResult<GetExhibitorData_Result> GetExhibitorData()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetExhibitorData_Result>("GetExhibitorData");
        }
    
        public virtual ObjectResult<GetTotalCoupon_Result> GetTotalCoupon()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetTotalCoupon_Result>("GetTotalCoupon");
        }
    }
}
